{{- if .Values.vault_settings.gcp_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-db-host/versions/latest" 
        fileName: "database-host"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-ai-fusion-db-user/versions/latest" 
        fileName: "ai-fusion-db-user"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-ai-fusion-db-password/versions/latest" 
        fileName: "ai-fusion-db-password"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-ai-fusion-db/versions/latest" 
        fileName: "ai-fusion-db"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/message-broker-driver/versions/latest" 
        fileName: "message-broker-driver"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-message-broker-connection-string/versions/latest" 
        fileName: "message-broker-connection-string"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-app-secret-key/versions/latest" 
        fileName: "app-secret-key"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/keycloak-certs-endpoint/versions/latest" 
        fileName: "keycloak-certs-endpoint"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-epam-dial-api-key/versions/latest" 
        fileName: "epam-dial-api-key"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-azure-api-key/versions/latest" 
        fileName: "azure-api-key"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-openai-api-key/versions/latest" 
        fileName: "openai-api-key"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-google-api-key/versions/latest" 
        fileName: "google-api-key"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-aws-bedrock-api-key/versions/latest" 
        fileName: "aws-bedrock-api-key"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-aws-bedrock-access-key-id/versions/latest" 
        fileName: "aws-bedrock-access-key-id"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-aws-bedrock-region/versions/latest" 
        fileName: "aws-bedrock-region"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_ai_fusion.secretName }}
      type: Opaque
      data:
      - objectName: "google-api-key"
        key: google-api-key
      - objectName: "aws-bedrock-api-key"
        key: aws-bedrock-api-key
      - objectName: "aws-bedrock-access-key-id"
        key: aws-bedrock-access-key-id
      - objectName: "aws-bedrock-region"
        key: aws-bedrock-region
      - objectName: "openai-api-key"
        key: openai-api-key
      - objectName: "azure-api-key"
        key: azure-api-key
      - objectName: "epam-dial-api-key"
        key: epam-dial-api-key
      - objectName: "keycloak-certs-endpoint"
        key: keycloak-certs-endpoint
      - objectName: "app-secret-key"
        key: app-secret-key
      - objectName: "message-broker-connection-string"
        key: message-broker-connection-string
      - objectName: "message-broker-driver"
        key: message-broker-driver
      - objectName: "database-host"
        key: database-host
      - objectName: "ai-fusion-db-user"
        key: user
      - objectName: "ai-fusion-db-password"
        key: password
      - objectName: "ai-fusion-db"
        key: database-db
{{- end }}
