{{- if .Values.vault_settings.aws_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.vault_settings.aws_secret_manager_region }}
    objects: |
      - objectName: "app-secret-key"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "ai-fusion-db-user"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "ai-fusion-db-password"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "db-host"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "ai-fusion-db"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "message-broker-driver"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "message-broker-connection-string"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "keycloak-certs-endpoint"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "epam-dial-api-key"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "azure-api-key"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "openai-api-key"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "google-api-key"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "aws-bedrock-api-key"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "aws-bedrock-access-key-id"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "aws-bedrock-region"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_ai_fusion.secretName }}
      type: Opaque
      data:
        - objectName: "aws-bedrock-access-key-id"
          key: aws-bedrock-access-key-id
        - objectName: "aws-bedrock-region"
          key: aws-bedrock-region
        - objectName: "epam-dial-api-key"
          key: epam-dial-api-key
        - objectName: "azure-api-key"
          key: azure-api-key
        - objectName: "openai-api-key"
          key: openai-api-key
        - objectName: "google-api-key"
          key: google-api-key
        - objectName: "aws-bedrock-api-key"
          key: aws-bedrock-api-key
        - objectName: "ai-fusion-db-user"
          key: user
        - objectName: "ai-fusion-db-password"
          key: password
        - objectName: "db-host"
          key: database-host
        - objectName: "ai-fusion-db"
          key: database-db
        - objectName: "app-secret-key"
          key: app-secret-key
        - objectName: "message-broker-driver"
          key: message-broker-driver
        - objectName: "message-broker-connection-string"
          key: message-broker-connection-string
        - objectName: "keycloak-certs-endpoint"
          key: keycloak-certs-endpoint
{{- end }}
