ai_fusion:
  image:
    path: "/deps-platform/deps-ai-fusion"
  resources: {}


ai_fusion_settings:
  ENV: other

  LOG_LEVEL: "INFO"

  DATABASE_REQUIRE_SECURE_TRANSPORT: false


migration_settings:
  DATABASE_REQUIRE_SECURE_TRANSPORT: false

ai_fusion_consumer:
  image:
    path: "/deps-platform/deps-ai-fusion"

ai_fusion_agent:
  image:
    path: "/deps-platform/deps-ai-fusion"


migrator:
  image:
    path: "/deps-platform/deps-ai-fusion-migrator"


helm:
  helm_logs_job_enabled: false


csi:
  vault_namespace: 'k8s-other'
  roleName: 'k8s-other'
  vaultKubernetesMountPath: 'kubernetes-other'

service_account:
  serviceAccountName: 'deps-other'
